# Generated by Django 5.2.1 on 2025-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
