"""
Django settings for TournamentTracker project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url

# ------------------------
# BASE DIRECTORY
# ------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------
# SECURITY
# ------------------------
SECRET_KEY = config('SECRET_KEY', default='unsafe-secret-key')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = [
    'tournament-tracker-dgus.onrender.com',  # Render deployment
    '127.0.0.1',
    'localhost',
]

# ------------------------
# TIMEZONE & INTERNATIONALIZATION
# ------------------------
TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True
LANGUAGE_CODE = 'en-us'
USE_I18N = True

# ------------------------
# AUTH REDIRECTS
# ------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/badminton/'
LOGOUT_REDIRECT_URL = '/login/'

# ------------------------
# INSTALLED APPS
# ------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'badminton',
]

# ------------------------
# MIDDLEWARE
# ------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------
# URL & WSGI
# ------------------------
ROOT_URLCONF = 'TournamentTracker.urls'
WSGI_APPLICATION = 'TournamentTracker.wsgi.application'

# ------------------------
# TEMPLATES
# ------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'TournamentTracker' / 'templates',
            BASE_DIR / 'badminton' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------
# DATABASE
# ------------------------
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # PostgreSQL (Render or local) from DATABASE_URL
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False  # Change to True if Render enforces SSL
        )
    }
else:
    # Default fallback: SQLite (local dev if DATABASE_URL not set)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ------------------------
# PASSWORD VALIDATION
# ------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------
# STATIC FILES
# ------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ------------------------
# DEFAULT AUTO FIELD
# ------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------
# OPTIONAL: Local Development ENV VARS (if using .env)
# ------------------------
# Example .env for local development:
# DATABASE_URL=postgres://myuser:mypassword@localhost:5432/mydatabase
# SECRET_KEY=unsafe-secret-key
# DEBUG=True
