"""
Django settings for TournamentTracker project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
import dj_database_url
# ✅ Timezone
TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

# ✅ Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ SECURITY
SECRET_KEY = 'django-insecure-6aresfgq9c=oglb0_8vq1y4jgom*&)oup2e&14$80_z6!!2fch'
DEBUG = False  # ⚠️ Set to False in production
ALLOWED_HOSTS = ['tournament-tracker-dgus.onrender.com', '127.0.0.1']

# ✅ Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/badminton/'
LOGOUT_REDIRECT_URL = '/login/'

# ✅ Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'badminton',
]

# ✅ Middleware (include WhiteNoise)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Required to serve static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ✅ URL config
ROOT_URLCONF = 'TournamentTracker.urls'

# ✅ Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'TournamentTracker' / 'templates',
            BASE_DIR / 'badminton' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ✅ WSGI application
WSGI_APPLICATION = 'TournamentTracker.wsgi.application'

# ✅ Database
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),  # Automatically picks from env var
        conn_max_age=600,
        ssl_require=True
    )
}
# ✅ Optional: custom 403 handler (if implemented)
# HANDLER403 = 'your_app.views.permission_denied'

# ✅ Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ✅ Language and internationalization
LANGUAGE_CODE = 'en-us'
USE_I18N = True

# ✅ Static files settings (for CSS, JS, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic puts files

# ⚠️ DO NOT add STATICFILES_DIRS since you're using app/static/ folders (like badminton/static/)
# Django collects those automatically with AppDirectoriesFinder

# ✅ WhiteNoise setting for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ✅ Default auto primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
